import { Router } from "express";
import UNPAIDTRANSACTION_HANDLER from "./unpaidTransaction.handler";


const UNPAIDTRANSACTION_ROUTER=Router();

UNPAIDTRANSACTION_ROUTER.post("/add",UNPAIDTRANSACTION_HANDLER.add);
UNPAIDTRANSACTION_ROUTER.put("/update/:id",UNPAIDTRANSACTION_HANDLER.update);
UNPAIDTRANSACTION_ROUTER.get("/all",UNPAIDTRANSACTION_HANDLER.all);
UNPAIDTRANSACTION_ROUTER.get("/:id",UNPAIDTRANSACTION_HANDLER.id);


export default UNPAIDTRANSACTION_ROUTER;